import React from 'react';
import FooterOne from '../common/footer/FooterOne';
import HeaderTwo from '../common/header/HeaderTwo';
import CtaLayoutOne from '../component/cta/CtaLayoutOne';
import BreadCrumbOne from '../elements/breadcrumb/BreadCrumbOne';
import ColorSwitcher from '../elements/switcher/ColorSwitcher';
import SEO from '../common/SEO';

const TermsOfUse = () => {
    return (
        <>
            <SEO title="Terms & Conditions" />
            <main className="main-wrapper">
                <HeaderTwo />
                <BreadCrumbOne
                    title="Terms & Conditions"
                // page="Terms & Conditions"
                />
                <div className="section-padding privacy-policy-area">
                    <div className="container">
                        <div className="row justify-content-center">
                            <div className="col-lg-10">
                                <div className="privacy-policy-content">
                                    <h6>1. Introduction</h6>
                                    <ol>
                                        <p><li> <strong> THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF THE INFORMATION TECHNOLOGY ACT, 2000 AND RULES MADE THEREUNDER. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.</strong></li></p>
                                        <p> <li><strong>THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF RULE 3(1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES GUIDELINES AND DIGITAL MEDIA ETHICS CODE) RULES, 2021 THAT REQUIRES PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND Terms & Conditions FOR ACCESS OR USAGE OF THE PLATFORM </strong> </li></p>
                                        <p> <li>  Set forth herein the terms and conditions that apply to the access and use of the domain name littlemoneyindia.com. littlemoney.co.in and its related sub-domains, sites, services, tools and its associated mobile applications (collectively, the "Platform") is owned, managed and operated by Little Money Technologies Private Limited, a private company incorporated under the Companies Act, 2013 with its registered office at #30/1, 4th Cross Road, New Bank colony, Konanakunte, Bangalore, Bangalore, Karnataka, India, 560062 (hereinafter referred to as "we", "our" or "LittleMoney" which expression shall, unless it be repugnant to the context or meaning thereof, be deemed to include its successors, affiliates, and permitted assigns) and by "you" we refer to the users of the Platform.</li></p>
                                        <p><li>Please read these Terms of Service carefully ("Terms" or "Terms of Service"), as it contains the terms and conditions governing your use of the Platform and any content such as text, data, information, software, graphics, audio, video or photographs etc. that LittleMoney may make available through the Platform and any services that LittleMoney may provide through the Platform. In order to use the Platform, you must first agree the Terms. By accessing, browsing or otherwise using the Platform, you are agreeing to be bound by the Terms and concluding a legally binding contract with LittleMoney. Please do not access or use the Platform if you do not agree with any of the Terms provided below or are unable to be bound by them. In addition, if you visit any of our partners' websites/ platforms or arrive at our Platform through one of our many partners' websites/ platforms, you may also be subject to the terms and conditions of the website/ platform of our partners. As a condition of your access to and use of the Platform, you hereby agree that you will comply with all applicable laws and regulations when using the Platform.</li></p>
                                        <p><li>LittleMoney reserves the right, at its sole discretion, to change, modify, add or remove portions of these Terms of Service, at any time and will notify you by email or post a conspicuous notice on the Platform in the event of any material revisions to these Terms. It is your sole responsibility to review these Terms periodically for updates or changes. Your continued use of the Platform following the posting of changes shall be deemed to mean that you accept and agree to the revisions made to the Terms of Service. As long as you comply with these Terms, LittleMoney grants you a personal, revocable, non-exclusive, non-transferable, limited privilege to access and use the Platform.</li> </p>
                                        <p><li>You should read the Terms and access and read all further linked information, if any, referred to in these Terms, as such information contains further terms and conditions that apply to you as a user of the Platform. </li></p>
                                        <p><li> If you are unwilling or unable to be legally bound by these Terms, please do not use the Platform. You cannot accept these Terms if: (a) you are not lawfully entitled to use the Platform or (b) if you are not of legal age to form a binding agreement with LittleMoney.</li></p>
                                        <p><li>Such linked information including but not limited to LittleMoney' privacy policy ("Privacy Policy") is hereby incorporated by reference into these Terms.</li></p>
                                    </ol>

                                    <h6>2. Membership Eligibility</h6>
                                    <p>Use of the Platform is available only to persons who can enter into legally binding contracts under the Indian Contract Act, 1872 and is not a person barred from receiving services under the laws of India or other applicable jurisdiction. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents and persons of unsound mind are not eligible to use the Platform. Any person under the age of 18 (eighteen) shall not register on the Platform and shall not transact on or use the Platform. If a minor wishes to use or transact on the Platform, such use or transaction may be made by the minor's legal guardian or parents on the Platform. LittleMoney reserves the right to terminate any person's membership and/or refuse to provide such person with access to the Platform if it is brought to the notice of LittleMoney or if LittleMoney discovers for itself that such person is not eligible to use the Platform.</p>

                                    <h6>3. Acceptance of Terms</h6>
                                    <ol>
                                        <p><li>LittleMoney, hereby, provides an independent online service which facilitates your access to information primarily about loans and related financial services and other products or services provided by our partner financial institutions whilst using this Platform. We receive a fee and/or commission from such partners when you use our service to purchase products or avail services from them. Please carefully read these Terms. By accessing or using the Platform, you are agreeing to these Terms and concluding a legally binding contract with LittleMoney.</li></p>
                                        <p><li>LittleMoney does not charge any registration/ membership or browsing fee...</li></p>
                                        <p><li>In order to use the Platform, you must first agree to the Terms...</li></p>
                                    </ol>

                                    <h6>4. Opening an Account</h6>
                                    <p>The Platform allows only limited and restricted access to the services for unregistered users. In order to use the Platform, you will have to create an account by signing up on the Platform ("Account"), which can be done by providing/ using the following: (a) your cell phone number with password; or (b) email address with password; or (c) google or other social media logins; or (d) such other login credentials that are adopted by the industry for setting up an Account with the Platform. Upon entering the required details, you may either receive a "One Time Password" (OTP) for the purpose of verification or your Account or your Account may be verified by using the google or other social media logins or such other auto verification process adopted by the industry, and upon completion of verification, the Account is created and is ready for use. You shall not transfer or share your Account information with anyone or create more than one Account</p>

                                    <h6>5. Username and Password</h6>
                                    <ol>
                                        <p><li>Once registered, in order to log into the Account on the
                                            Platform, you will be required to provide the following: (a) your cell phone number with password; or (b) email address with password; or (c) google or facebook social logins; or (d) such other login credentials that are adopted by the industry for logging into the Account with the Platform used at the time of signing-up ("Login Credentials"). Upon being successfully registered on the Platform you will be provided access to a dashboard which shall enable you to access your account details and details of the loans applied for.
                                        </li></p>
                                        <p><li>You shall be solely responsible for maintaining confidentiality of the Login Credentials, and to the extent allowed by law, you hereby accept responsibility for all activities on the Account authenticated through the Login Credentials, whether authorized or not. You agree to keep Login Credentials confidential and secure, and you shall not give or make Login Credentials available, directly or indirectly, to any unauthorized individual. You acknowledge and agree that if you allow, whether through action or inaction, a person to gain access to the Login Credentials, with or without permission, you are authorizing that person to use the Platform through the Account, and you shall be responsible for all actions that result from such access, even if you did not want the actions performed, and even if they are unauthorized or fraudulent. LittleMoney shall not be held liable in any manner whatsoever for lack of any such authorization whilst creating the Account.</li></p>
                                        <p><li>LittleMoney cannot and will not be liable for any loss or damage arising from or arising out of your use of the Platform, theft of the Login Credentials, use of the Login Credentials or release of the Login Credentials to a third party or your authorization to allow another person to access and use the Platform using the Account.</li></p>
                                        <p><li>In case of any misappropriation or unauthorised access of the Account, you agree to communicate the same to LittleMoney immediately. You shall further ensure that you exit/ logout from the Account at the end of each session. LittleMoney shall not be liable for any loss or damage arising from your failure to comply with this provision. You may be held liable for losses incurred by LittleMoney or any user or visitor of the Platform due to authorised or unauthorised use of the Account, as a result of your failure in keeping the Login Credentials confidential.</li></p>
                                        <p><li>You agree that the information provided by you to LittleMoney, at all times (including during registration), will be true, accurate, up-to-date, and complete. You further agree that if you provide any information that is untrue, inaccurate, not up-to-date or incomplete or becomes untrue, inaccurate or incomplete or if LittleMoney has reasonable grounds to suspect that such information is untrue, inaccurate, not up-to-date, incomplete or not in accordance with the these Terms, LittleMoney shall have the right to indefinitely suspend or terminate or block access to the Account on the Platform and refuse to provide you access to the Platform. You are advised to use due caution when providing any information to LittleMoney accordingly.</li></p>
                                    </ol>

                                    <h6>6. Agreement to receive Communication</h6>
                                    <ol>
                                        <p><li>You hereby by way of accepting these Terms consent to the receipt of communication from LittleMoney and its business partners by way of Short Message Service (SMS) messages, e-mails, promotional, marketing calls and newsletters. These emails could relate to your registration, transactions that you carry out through the Platform and promotions that are undertaken by LittleMoney.</li></p>
                                        <p><li>LittleMoney and its business partners may, from time to time, announce certain offers with intent to promote its Platform and/or services ("Promotional Offer(s)"). The Promotional Offer(s) would always be governed by these Terms of Service plus certain additional terms and conditions, if any prescribed. The said additional terms and conditions, if prescribed, would be specific to the corresponding Promotional Offer only and shall prevail over these Terms of Service, to the extent they may be in conflict with these Terms of Service. LittleMoney reserves the right to withdraw, discontinue, modify, extend and suspend the Promotional Offer(s) and the terms governing it, at its sole discretion.</li></p>
                                    </ol>

                                    <h6>7. Links to Third Party Websites</h6>
                                    <p>The Platform may contain or provide links and interactive functionality interacting with the websites or resources of third parties. Since LittleMoney has no control over such third-party websites and resources, you acknowledge and agree that LittleMoney is not responsible for and has no liability for the functionality, actions, inactions, privacy settings, privacy policies, terms, or content of any such websites or resources. You further acknowledge and agree that Your interaction with any third party accessed through the Platform is at your own risk and LittleMoney shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such webite or resource. Before enabling any sharing functions to communicate with any such website or otherwise visiting any such website, LittleMoney strongly recommends that you review and understand the terms and conditions, privacy policies, settings, and information-sharing functions of each such third-party website.</p>

                                    <h6>8. Use of the Platform</h6>
                                    <ol>
                                        <p><li>1.	You agree, undertake and covenant that, during the use of the Platform, you shall not host, display, upload, modify, publish, transmit, store, update or share any information that:
                                            <ol type='a'>
                                                <li>
                                                    <p>belongs to another person or entity and to which you do not have any right;</p>
                                                </li>
                                                <li>
                                                    <p>is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another person's privacy, insulting or harassing on the basis of gender, hateful or racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent or contrary to the laws in force in any manner whatsoever.</p>
                                                </li>
                                                <li>
                                                    <p>isharmful to children;</p>
                                                </li>
                                                <li><p>is misleading in any way;</p></li>
                                                <li><p>involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";</p></li>
                                                <li><p>infringes upon or violates any third party's rights including, but not limited to, any patent, trademark, copyright or other proprietary rights or intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number);</p></li>
                                                <li><p>Impersonates another person or provides instructional information about illegal activities such as violating someone's privacy or providing or creating computer viruses;</p></li>
                                                <li><p>tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, or other areas of the Platform or solicits passwords or personally identifying information for commercial or unlawful purposes from other users of the Platform;</p></li>
                                                <li><p>engages in commercial activities without LittleMoney' prior written consent such as engages in contests, sweepstakes, barter, advertising etc;</p></li>
                                                <li><p>interferes with another user's use of the Platform;</p></li>
                                                <li><p>refers to any website or URL that, in LittleMoney' sole discretion, contains material that is inappropriate for the Platform or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms;</p></li>
                                                <li><p>deceives or misleads the addressee/ users about the origin of the messages or knowingly and intentionally communicates any information which is patently false or misleading or grossly offensive or menacing in nature but may reasonably be perceived as a fact;</p></li>
                                                <li><p>contains software viruses or any other computer codes, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms or other computer programming routines that may damage, detrimentally interfere with, diminish value of, covertly intercept or steal any system, data or personal information;</p></li>
                                                <li><p>threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting other nation;</p></li>
                                                <li><p>is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person; and</p></li>
                                                <li><p>violates any law for the time being in force.</p></li>

                                            </ol>
                                            <li>In no event and under no circumstances shall LittleMoney be held liable to you for any liabilities or damages resulting from or arising out of your use of the Platform. You shall not use anyone else's account at any time.</li>
                                        </li></p>

                                    </ol>

                                    <h6>9. Users Posts and Reviews</h6>
                                    <ol>
                                        <p><li>The Platform may allow you to post certain content, data or information belonging to you, such as reviewing and allowing you to share your experience and views about a particular product/ service, and rate product/ service, post your comments and reviews in relation to the product/ service on the Platform on specific pages of the Platform, as well as submit/ post any suggestions, comments, questions or other information to LittleMoney using the Platform (collectively referred to "User Content").</li></p>
                                        <p><li>You, being the originator of the User Content, are responsible for the User Content that you upload, post, publish, transmit or otherwise make available on the Platform. You represent and covenant that you have obtained all relevant consents and approvals in order to post any User Content and shall not post any content relating to or owned by a third party for the promotion or sale of products/ services of such third party. You further represent that all such User Content will be in accordance with applicable laws. By sharing or submitting any content including any data and information on the Platform, you agree that you shall be solely responsible for all content you post on the Platform and LittleMoney shall neither be responsible or liable for any User Content you make available on or through the Platform nor endorse any User Content on the Platform. LittleMoney reserves the right to remove any third-party marketing material and disable access to the User Content on the Platform.</li></p>
                                        <p><li>You hereby grant LittleMoney a perpetual, non-revocable, worldwide, royalty-free and sub-licensable right and license to use, copy, distribute, display, publish, transmit, make available, reproduce, modify, adapt the User Content and create derivate works of the User Content. You represent and warrant that you own or otherwise control all of the rights to the User Content that you post or that you otherwise provide on or through the Platform; and that, as at the date that the User Content is posted or submitted on the Platform: (i) the User Content is accurate; (ii) use of the User Content you supply does not breach these Terms; and (iii) that such User Content is lawful.</li></p>
                                        <p><li>You further represent and warrant that while posting any User Content on the Platform you shall not use any unlawful, offensive, libellous, derogatory, hateful or racially or ethnically objectionable language or other material or content that would violate rights of publicity and/or privacy or that would violate any applicable law; (ii) any commercial material or content (including, but not limited to, solicitation of funds, advertising, or marketing of any good or services); and (iii) any material or content that infringes, misappropriates or violates any copyright, trademark, patent right or other proprietary right of any third party. You shall be solely liable for any damages resulting from any violation of the foregoing restrictions, or any other harm resulting from your posting of content to this Platform.</li></p>
                                    </ol>

                                    <h6>10. Content and Intellectual Property Rights</h6>
                                    <ol>
                                        <p><li>Except for User Content, all of the content and services and products provided on the Platform, including text, software, scripts, code, designs, graphics, photos and other content and the copyrights, trademarks, service marks, logos, trade names, and other intellectual and proprietary rights associated therewith is owned by LittleMoney or others (including without limitation, the third party service providers or participants) that LittleMoney licenses such content from, and is protected by copyright, trademark, patent and other intellectual property laws.</li></p>
                                        <p><li>You hereby acknowledge that the services constitute original works and have been developed, compiled, prepared, revised, selected, and arranged by LittleMoney and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable intellectual property of LittleMoney and such others. You thereby agree to protect the proprietary rights of LittleMoney during and after the term of these Terms. You may not selectively download portions of the Platform without retaining the copyright notices or modify it, or any portion of it, except with express written consent of LittleMoney. You may download material from the Platform only for your own personal use and for no commercial purposes whatsoever.</li></p>
                                        <p><li>This Platform or any portion of this Platform (including but not limited to any copyrighted material, trademarks, or other proprietary information) may not be reproduced, duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any commercial purpose without express written consent of LittleMoney.</li></p>
                                        <p><li>Any infringement shall lead to appropriate legal proceedings against you at an appropriate forum for seeking all available remedies under applicable laws of the country.</li></p>
                                    </ol>

                                    <h6>11. Termination of access to the Platform</h6>
                                    <ol>
                                        <p><li>Your Account can be terminated at any time by:
                                            <ol type='a'>
                                                <p><li>You, by ceasing to use the Platform.</li></p>
                                                <p><li>LittleMoney, in its sole discretion for any reason or no reason, including your violation of these Terms or lack of use of Platform. You acknowledge that the termination of access to the Platform may be affected without any prior notice, and LittleMoney may immediately deactivate or delete the Account and all related information and/or bar any further access to the Account or the services.</li></p>
                                            </ol>
                                        </li></p>

                                    </ol>

                                    <h6>12. Referrals and Rewards</h6>
                                    <p>From time to time, LittleMoney may offer referral bonuses and rewards to you for inviting new users to the platform and for completing other activities.</p>

                                    <h6>13. Rights & Reservations</h6>
                                    <ol>
                                        <p><li>LittleMoney reserves the right to:
                                            <ol type='a'>
                                                <p><li>Make all decisions in relation to inter alia your registration with LittleMoney;</li></p>
                                                <p><li>Give you a username, different from the username chosen by you, if it impersonates an already existing username, or if LittleMoney feels it is otherwise inappropriate;</li></p>
                                                <p><li>Request additional documents and additional information from you for the purpose of your registration as a user with the Platform; and</li></p>
                                                <p><li>Deny access to the Platform or any portion thereof without notice for the following reasons (i) any unauthorized access or use by you (ii) attempt(s) to assign or transfer any rights granted to you under these Terms; (iii) violation of any of the provisions of the Terms or any applicable laws.</li></p>
                                            </ol>
                                        </li>
                                        </p>
                                    </ol>

                                    <h6>14. Disclaimer of Warranties</h6>
                                    <p>THE PLATFORM AND ALL INFORMATION, CONTENT, MATERIALS AND SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE PLATFORM ARE PROVIDED BY LITTLEMONEY ON AN "AS IS," "AS AVAILABLE" BASIS, WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. LITTLEMONEY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE PLATFORM, THE ACCURACY OR COMPLETENESS OF THE CONTENT AND THE ACCURACY OF THE INFORMATION. LITTLEMONEY SHALL HAVE NO RESPONSIBILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY CONTENT, MATERIALS, DOCUMENTS OR INFORMATION. YOU EXPRESSLY AGREE THAT THE USE OF THE PLATFORM IS AT YOUR OWN DISCRETION AND SOLE RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE RESULTING FROM ANY TRANSACTION. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM LITTLEMONEY OR THROUGH OR FROM THE PLATFORM OR CONTENT SHALL CREATE ANY WARRANTY. LITTLEMONEY WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE PLATFORM OR THE CONTENT INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, CONSEQUENTIAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE SPECIFIED IN WRITING. TO THE FULL EXTENT PERMITTED BY LAW, LITTLEMONEY DISCLAIMS ANY AND ALL REPRESENTATIONS AND WARRANTIES WITH RESPECT TO THE PLATFORM AND IT'S CONTENT, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE OR USE. FURTHER, LITTLEMONEY AND ITS SERVICE PROVIDERS, AFFILIATES, BUSINESS PARTNERS MAKE NO WARRANTY THAT (I) THE SERVICES WILL MEET YOUR REQUIREMENTS, (II) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (III) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE, (IV) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS, AND (V) ANY ERRORS IN THE TECHNOLOGY WILL BE CORRECTED.  </p>

                                    <h6>15. Limitation of Liability</h6>
                                    <p>IN NO EVENT SHALL LITTLEMONEY, OR [ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES AND GROUP COMPANIES] BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR LOSS OF PROFIT OR REVENUES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE PLATFORM; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF THE SECURE SERVERS AND/OR ANY AND ALL PERSONAL AND/OR BUSINESS AND/OR FINANCIAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES ON THE PLATFORM; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH THE PLATFORM BY ANY THIRD PARTY; (VI) [ANY LOSS OF YOUR DATA OR CONTENT FROM THE SERVICES, YOUR FAILURE TO KEEP LOGIN CREDENTIALS OR ACCOUNT DETAILS SECURE AND CONFIDENTIAL; AND/OR (VII) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT LITTLEMONEY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LITTLEMONEY SHALL NOT BE LIABLE UNDER ANY CIRCUMSTANCES FOR DAMAGES ARISING OUT OF OR IN ANY WAY RELATED TO PRODUCTS, SERVICES AND/OR INFORMATION OFFERED OR PROVIDED BY THIRD-PARTY VENDORS ACCESSED THROUGH THE PLATFORM.</p>

                                    <h6>16. Indemnification</h6>
                                    <p>You shall indemnify and hold harmless LittleMoney, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any and all claims or demands, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms, Privacy Policy and other policies, or your violation of any law, rules or regulations or the rights (including infringement of any intellectual property rights) of a third party.</p>

                                    <h6>17. Privacy Policy</h6>
                                    <p>By using the Platform, you hereby consent to the use of your information as we have outlined in our Privacy Policy. The Privacy Policy explains how LittleMoney treats your personal information when you access the Platform and use other ancillary services. Please review the Privacy Policy, which also governs your visit to the Platform, to understand LittleMoney' practices. The personal information/data provided to LittleMoney by you during the course of usage of the Platform will be treated as strictly confidential and in accordance with the Privacy Policy and applicable laws and regulations. If you object to your information being transferred or used, please do not use the Platform..</p>

                                    <h6>18. Assignment</h6>
                                    <p>LittleMoney reserves the right, at its own discretion, to freely assign and transfer the rights and obligations under these Terms to any third party.</p>

                                    <h6>19. Governing Law</h6>
                                    <p>These Terms shall be governed by and interpreted and construed in accordance with the laws of India. The juridical seat and venue of jurisdiction shall exclusively be in Bangalore, India. In the event of any dispute arising out of these Terms the same shall be settled by a binding arbitration conducted by a sole arbitrator, appointed jointly by both parties and governed by the Arbitration and Conciliation Act, the venue of arbitration shall be Bangalore, India.</p>

                                    <h6>20. Severability and Waiver</h6>
                                    <p>These Terms, the Privacy Policy and other referenced material herein or on the Platform, are the entire agreement between you and LittleMoney with respect to the products/services offered on the Platform and supersede all prior or contemporaneous communications and proposals (whether oral, written or electronic) between you and LittleMoney with respect thereto and govern the future relationship. If any provision of the Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Terms will otherwise remain in full force and effect and enforceable. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.</p>

                                    <h6>21. Grievance Redressal Officer</h6>
                                    <p>In accordance with the Information Technology Act, 2000 and Rules made thereunder, the name and contact details of the officer (" Grievance Officer") are provided below:</p>
                                    <p>Name: Gajendra Sangappa</p>
                                    <p>Address: #30/1, 4th Cross Road, New Bank colony, Konanakunte, Bangalore, Karnataka, India, 560062</p>
                                    <p>Cell: +91-9513993655</p>
                                    <p>Email ID: <a href="mailto:support@littlemoney.co.in">support@littlemoney.co.in</a></p>

                                    <h6>22. How to Contact LittleMoney</h6>
                                    <p>If you have questions or concerns about these Terms of Service, please contact LittleMoney at: <a href="mailto:admin@littlemoney.co.in">admin@littlemoney.co.in</a></p>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {/* <CtaLayoutOne /> */}
                <FooterOne parentClass="" />
            </main>
        </>
    )
}

export default TermsOfUse;
